global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eva01'
    static_configs:
      # For macOS/Windows Docker Desktop, use host.docker.internal
      # For Linux, you may need to use the host's IP or network_mode: host
      - targets: ['host.docker.internal:9000']
        labels:
          instance: 'eva01-local'

